name: Lint Notebooks

on:
  push:
    branches:
      - CI-CD
    paths:
    - '**.ipynb'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install nbqa flake8
    - name: Lint .ipynb files
      run: |
        nbqa flake8 **/*.ipynb
